### PR TITLE
optimized DNF + fix

### PR DESCRIPTION
**Pull request by PashaSmirnov**
Fixed dnf optimization by placing handleRecursively and optimzed answer size by removing subset, which is oppisite to what was before.

### CODE REVIEW

**Comment by stiv-yakovenko** [comment]
Please don't forget to run tests from console java file there.

**Comment by PashaSmirnov** [comment]
I fixed one test since its answer size is now optimized.
But is the following test correct?
Seems like expected answer has conepts out of target signature.
https://github.com/stiv-yakovenko/defind/blob/1591274d555bb8b871172076c7581aed1b19ac8c/src-console/test/ConsoleTest.java#L125

**Comment by PashaSmirnov** [comment]
It doesn't work for me even at older revisions, but for some reasoner's reasons. It just can't find a proof.

**Comment by stiv-yakovenko** [comment]
ask Denis, I have no idea :(

**Pull request merged**
